### ISSUE TITLE
100% Reproducible crash on launch

### ISSUE THREAD

**Issue by alexanderustwo** [bluecats/bluecats-ios-sdk#7]
We are experiencing a 100% reproducible crash when firing up the BlueCats SDK.
XCode version 7.3 (7D175)

Attached is a sample project that has added the BlueCats SDK as a dependency using cocoapods.
Pods are already installed in the zip file provided.

The minimal code triggering the crash can be found in the AppDelegate, and looks like this:

`BlueCatsSDK.startPurringWithAppToken(/*Enter API Key Here*/) { 
    status in
    print("Status: \(status)")
}`

Replace the "Enter API Key Here" comment with a valid API key and run the app and it will crash with the following message:

`+[BlueCatsSDK getBCInstallationIdProtocol]: unrecognized selector sent to class 0x10d95fc98`

What is even more intriguing is that if you include the "Fabric" pod via cocoapods this crash does not occur anymore, even if the included Fabric pod is not even used.

To reproduce this, uncomment the Fabric line in the Podfile and run `pod install`. Launch the workspace and run the project. You might want to clean the project before running, to be 100% sure everything is up to date and in sync.

[BlueCats-Crash.zip](https://github.com/bluecats/bluecats-ios-sdk/files/218778/BlueCats-Crash.zip)

**Comment by caseycoding** [comment]
Hi Alexander,

It looks like the issue is due to the 'use frameworks!' line in your podfile.  I'm not sure why this works once fabric is added, but this repo only contains a static lib version of our SDK.  I'll add you to a private repo with our SDK release candidate which includes a framework.  After updating your podfile and importing the framework into the app delegate, you should be good to go.  Email us at support@bluecats.com if you have any questions or issues.

**Comment by damoclarke** [comment]
Hi Alexander,

I have just tested another work-around for this issue is to add -all_load to the Other Linker Flags build setting for your app. This fixes the problem when using the static library in your sample project. Potentially adding the Fabric pod may add this flag automatically.
