### ISSUE TITLE
Missing Gemfile with CocoaPods version

### ISSUE THREAD

**Issue by mgrebenets** [bluecats/bluecats-ios-sdk#9]
I have to mirror GitHub repo internally (for all kinds of reasons, including security).
So I have to run `pod spec lint` and `por repo push` commands. 

However, since my default CocoaPods version is `1.0.0` these commands fail.
It looks like current BlueCats podspec was created for older CocoaPods version. `0.39.0`. worked for me.

It would be super helpful if the repository would include both `Gemfile` and `Gemfile.lock` specifying exact CocoaPods version for the project, so that people like me can just run `bundle exec pod spec lint...`

Example `Gemfile` could look like this
```ruby
source 'https://rubygems.org'
gem 'cocoapods', '0.39.0'
```

**Comment by damoclarke** [comment]
Hi @mgrebenets. We have released 2.0.0 version of the SDK https://github.com/bluecats/bluecats-ios-sdk/releases/tag/2.0.0 and the pod spec lint passes with either version 0.39.0 or 1.0.0. We have decided to keep the existing format of the static library and podspec for this release rather than the two podspecs in the latest release candidate. 

This is to keep the implementation simple for customers and to maintain backwards compatibility as providing a dynamic framework via cocoapods still has a number of complications as you have found in the issues raised with the release candidates. We may provide a provide a dynamic framework version for manual install as an embedded framework in the future if this is required. Let us know if you have any trouble moving to the new version.
